### ISSUE TITLE
Vignette misspelled code in page 11

### ISSUE THREAD

**Issue by marceloavalostejeda** [heliosdrm/phia#2]
In the middle of page 11 you write:

> Then use this list to dene the contrasts in testInteractions (after renaming the columns of the
> matrices for a clearer interpretation of the output):
> 
> names(custom.contr$therapy) <- c("cntrl.vs.all", "T1.vs.T2")
> names(custom.contr$medication) <- c("plcb.vs.all", "D1.vs.D3", "D2.vs.avg")

But must be:

> **col**names(custom.contr$therapy) <- c("cntrl.vs.all", "T1.vs.T2")
> **col**names(custom.contr$medication) <- c("plcb.vs.all", "D1.vs.D3", "D2.vs.avg")

**Comment by heliosdrm** [comment]
Fixed time ago
